name: Unit Tests

on: [push] 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test
      - name: Run ESLint
        run: npm run lint
      - name: Generate JSdoc
        run: npm run doc
      - name: Commit and push generated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "🔄 Auto-generate docs on push [CI]" || echo "No changes to commit"
          git push
