name: Unit Tests

on: [push] 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run ESlint
        run: npm run lint
  JSdoc:
    env:
      GH_TOKEN: ${{ secrets.YYS_TOCKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Install Dependencies
        run: npm install
      - name: Generate JSdoc
        run: npm run doc
      - name: Commit and push generated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Auto-generate docs [CI]" || echo "No changes to commit"
          git push




