name: Unit Tests

on: [push] 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run ESlint
        run: npm run lint
  JSdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Generate JSdoc
        run: npm run doc



